server:
  port: 8080

spring:
  application:
    name: admin-api
  datasource:
    url: jdbc:mysql://localhost:3306/corporate_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: com.company.platform.repository

logging:
  level:
    com.company.platform: INFO

