server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tet?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

security:
  jwt:
    secret: please-change-me-very-long-secret
    expiration: 3600000

