server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:8024/corporate_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: constweak
    password: k9#Qz$mR!pX2@L8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

security:
  jwt:
    secret: please-change-me-very-long-secret
    expiration: 3600000

